// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, file_name, s3_url, file_size, file_type, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, file_name, s3_url, file_size, file_type, upload_date, last_accessed, is_public
`

type CreateFileParams struct {
	UserID   int32
	FileName string
	S3Url    pgtype.Text
	FileSize int64
	FileType pgtype.Text
	IsPublic pgtype.Bool
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.FileName,
		arg.S3Url,
		arg.FileSize,
		arg.FileType,
		arg.IsPublic,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.S3Url,
		&i.FileSize,
		&i.FileType,
		&i.UploadDate,
		&i.LastAccessed,
		&i.IsPublic,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, file_name, s3_url, file_size, file_type, upload_date, last_accessed, is_public
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.S3Url,
		&i.FileSize,
		&i.FileType,
		&i.UploadDate,
		&i.LastAccessed,
		&i.IsPublic,
	)
	return i, err
}

const getFilesByUserID = `-- name: GetFilesByUserID :many
SELECT id, user_id, file_name, s3_url, file_size, file_type, upload_date, last_accessed, is_public
FROM files
WHERE user_id = $1
ORDER BY upload_date DESC
`

func (q *Queries) GetFilesByUserID(ctx context.Context, userID int32) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.S3Url,
			&i.FileSize,
			&i.FileType,
			&i.UploadDate,
			&i.LastAccessed,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET file_name = $1, s3_url = $2, file_size = $3, file_type = $4, is_public = $5, last_accessed = NOW()
WHERE id = $6
RETURNING id, user_id, file_name, s3_url, file_size, file_type, upload_date, last_accessed, is_public
`

type UpdateFileParams struct {
	FileName string
	S3Url    pgtype.Text
	FileSize int64
	FileType pgtype.Text
	IsPublic pgtype.Bool
	ID       int32
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFile,
		arg.FileName,
		arg.S3Url,
		arg.FileSize,
		arg.FileType,
		arg.IsPublic,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.S3Url,
		&i.FileSize,
		&i.FileType,
		&i.UploadDate,
		&i.LastAccessed,
		&i.IsPublic,
	)
	return i, err
}
