// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID           int32
	UserID       int32
	FileName     string
	S3Url        pgtype.Text
	FileSize     int64
	FileType     pgtype.Text
	UploadDate   pgtype.Timestamp
	LastAccessed pgtype.Timestamp
	IsPublic     pgtype.Bool
}

type User struct {
	ID           int32
	Uuid         pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
